name: Deployment to Twilio Serverless

on: 
  push: 
     branches: 
        - main 

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [10]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and deploy
        run: |
          npm install
          npm run deploy -- --account-sid ${{secrets.ACCOUNT_SID}} --auth-token ${{secrets.AUTH_TOKEN}} --override-existing-project
          npm run jest
        env:
          CI: true

